sonar.organization=nikon11211
sonar.projectKey=nikon11211_secret-monitor
sonar.projectName=secret-monitor
sonar.sources=.
sonar.exclusions=**/*_test.go,examples/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=examples/**/*
